server:
  port: 8085
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true # 开启Feign对Sentinel的整合
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
#spring:
#  rabbitmq:
#    host: 192.168.44.128 # 你的虚拟机IP
#    port: 5672 # 端口
#    virtual-host: /hmall # 虚拟主机
#    username: hmall # 用户名
#    password: 123 # 密码