server:
  port: 8088
  tomcat:
    threads:
      max: 25 # 允许的最大线程数
    accept-count: 25 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-item
  swagger:
    title: "黑马商城搜索服务接口文档"
    package: com.hmall.search.controller
