# server配置
server:
  port: 8080
#spring:
#  application:
#    name: gateway
#  cloud:
#    nacos:
#      server-addr: 192.168.44.128:8848
#    gateway:
#      routes:
#        - id: item-service
#          uri: lb://item-service
#          predicates:
#            - Path=/items/**,/search/**
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/users/**,/addresses/**
#        - id: cart-service
#          uri: lb://cart-service
#          predicates:
#            - Path=/carts/**
#        - id: trade-service
#          uri: lb://trade-service
#          predicates:
#            - Path=/orders/**
#        - id: pay-service
#          uri: lb://pay-service
#          predicates:
#            - Path=/pay-orders/**
#      default-filters:
#        - AddRequestHeader=authorization, hechen
#        - PrintAny=1,2,3
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  auth:
    excludePaths:
      - /search/**
      - /users/login
      - /items/**
      - /hi
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123

