server:
  port: 8081
  tomcat:
    threads:
      max: 25 # 允许的最大线程数
    accept-count: 25 # 最大排队等待数量
    max-connections: 100 # 允许的最大连接
feign:
  okhttp:
    enabled: true
hm:
  db:
    database: hm-item
    host: mysql
    pw: 123
  swagger:
    title: "黑马商城商品服务接口文档"
    package: com.hmall.item.controller
